[package]
name = "mini_neural_network"
version = "0.1.0"
edition = "2024"

[dependencies]
ndarray = { version = "0.16.1", features = ["rayon"] }
ndarray-rand = "0.15.0"
ndarray-stats = "0.6.0"
rand = "0.9.0"

[dev-dependencies]
csv = "1.3.1"
ndarray-csv = "0.5.3"
