[package]
name = "mini_neural_network"
version = "0.1.0"
edition = "2024"

[dependencies]
ndarray = { version = "0.16.1", features = ["blas", "rayon"] }
ndarray-csv = "0.5.3"
ndarray-rand = "0.15.0"
rand = "0.9.0"
